# Generated by Django 3.1.7 on 2021-04-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210406_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='src',
            field=models.ImageField(default='/logo1.png', null=True, upload_to=''),
        ),
    ]
